name: pttms
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0
  location: ^6.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3  
  permission_handler: ^10.2.0
  equatable: ^2.0.5
  location_repository:
    path: ./packages/location_repository
  routes_repository:
    path: ./packages/routes_repository
  firebase_core: ^3.6.0
  dropdown_search: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.0.17


flutter:
  uses-material-design: true
