name: routes_repository
description: The Repo that handles mapping and location tracking
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.9.0
  location: ^6.0.2
  permission_handler: ^10.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.17

flutter:
  uses-material-design: true
  assets:
    - lib/routes.json
    